### ISSUE TITLE
Why Stencilのタイプミスを修正

### ISSUE THREAD

**Issue by kimulaco** [ionic-jp/stencil-docs#3]
翻訳プロジェクト参加前に翻訳済みのファイルを参考にしようと確認した際に、タイプミスを発見したため修正のPRを作成します。

## ファイル
src/docs_ja/introduction/why-stencil.md

## 修正内容
- `WEbコンポーエント` -> `Webコンポーネント`
- `ターゲッっと` -> `ターゲット`
- `また` が続く文章の修正案

**Comment by scrpgil** [comment]
大変、遅くなりました。
本日、マージさせていただきました。

**Comment by kimulaco** [comment]
ありがとうございます。
確認できたのでcloseします。
