### ISSUE TITLE
ドキュメントを出力するコマンドが抜けている

### ISSUE THREAD

**Issue by sam8helloworld** [ionic-jp/stencil-docs#64]
README.mdの

```
このサイトをビルドするには、まずこのリポジトリをcloneしてください。nodeおよびnpmの最新バージョンを使用していることを確認しておいてください。次に、 npm installと npm startを実行して、開発モードでサイトを起動します。
```

という箇所で`npm install`と`npm start`だけでは開発モードで各種ドキュメントのページには遷移できない。
`npm run docs`コマンドでドキュメントを出力する必要があるので、その記述を追加した方がいいかも。

**Comment by rdlabo** [comment]
closed with https://github.com/ionic-jp/stencil-docs/pull/65
